# Generated by Django 3.2.6 on 2023-04-10 11:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('last_login', models.DateTimeField()),
                ('role', models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='user_avatars/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
