# Generated by Django 3.2.6 on 2023-04-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_first_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name2',
        ),
    ]
